### ISSUE TITLE
ValueError: Shape (1, 600, 1000) must have rank 4

### ISSUE THREAD

**Issue by dorlow** [machrisaa/tensorzoom#2]
Hello, I have a little problem : wheni start net_analisys.py with a custom image (not the default cat beccause it works with it) python send me this error : 
`Traceback (most recent call last):
  File "net_analysis.py", line 103, in <module>
    render(pb_path='./results/tz6-s-stitch/tz6-s-stitch-gen.npy', img_path="./analysis/vt.jpg")
  File "net_analysis.py", line 50, in render
    net.build(contents)
  File "/home/alexandre/tensorzoom/tensorzoom_net.py", line 56, in build
    self.conv1 = self.conv_block(batch_img, 9, 3, 64, 1, 'conv1', trainable=self.conv_trainable)
  File "/home/alexandre/tensorzoom/tensorzoom_net.py", line 85, in conv_block
    conv = tf.nn.conv2d(input, filt, [1, strides, strides, 1], 'SAME')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 394, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2319, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1711, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 209, in conv2d_shape
    input_shape = op.inputs[0].get_shape().with_rank(4)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 641, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (1, 600, 1000) must have rank 4`
Thanks

**Comment by machrisaa** [comment]
Hi @dorlow, are your image `vt.jpg` a 600x100 greyscale image? can you send it to me to have a look?
